### ISSUE TITLE
Use `const` (and possibly `constexpr`)

### ISSUE THREAD

**Issue by h0nzZik** [kmzbrnoI/wsm-lib-cpp-qt#2]
Here, instead of
https://github.com/kmzbrnoI/wsm-lib-cpp-qt/blob/c8cbbf4505ad8a96da69476b87ff0a14297cce63/wsm.cpp#L79-L82
you may write
```c++
constexpr uint8_t MSG_SPEED = 0x1; 
constexpr uint8_t MSG_BATTERY = 0x2; 

const uint8_t type = (static_cast<uint8_t>(message[0]) >> 4) & 0x7; 
```
Because `const` means that the value of the variable does not change after initialization. But `constexpr` means that the value of this variable is allways the same - and that includes that its initializer is a constant expression. I believe you want to say here something like this:
> the variable for MSG_SPEED is only a symbolic name for the constant `0x01`

Note that this is C++-specific. For example, `const` in `C#` has similar meaning as `constexpr` in C++.

**Comment by malinajan** [comment]
Sure, this makes a perfect sense.
