### ISSUE TITLE
Use switch here

### ISSUE THREAD

**Issue by h0nzZik** [kmzbrnoI/wsm-lib-cpp-qt#3]
Use switch here instead of if-else-if
https://github.com/kmzbrnoI/wsm-lib-cpp-qt/blob/c8cbbf4505ad8a96da69476b87ff0a14297cce63/wsm.cpp#L83

And extract the parsing code into separate procedures - one for handling speed, other for handling battery.

**Comment by malinajan** [comment]
Done.
